# nixpacks.toml
[phases.setup]
nixPkgs = ['python3', 'pip']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['cd backend && python manage.py collectstatic --noinput']

[start]
cmd = './start.sh'
